import "../styles/globals.css";

import { TitleUpdater, Toolbar } from "../components";

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<head>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</head>
			<body className="relative flex min-h-screen bg-[rgb(250,250,250)] text-dark-he">
				<Toolbar />
				<div className="min-h-full flex-1">{children}</div>
			</body>
		</html>
	);
}
